### ISSUE TITLE
Changes made by Posten (again??!)

### ISSUE THREAD

**Issue by martin-andreassen** [reidarw/MMM-PostDelivery-Norway#5]
The module is not returning any values. It just states that it is "Loading.."

**Comment by tbarmo** [comment]
> The module is not returning any values. It just states that it is "Loading.."

I have the same here. Tried to delete the module and download it again, it still says "Loading..".

**Comment by reidarw** [comment]
Posten has started using a new API with a token that changes quite often

Example:
curl -X GET -H "Content-type: application/json" -H "**kp-api-token**: _f3508ef9MTY4MjY4NjMyMw_" https://www.posten.no/levering-av-post/_/service/no.posten. website/delivery-days?postalCode=7033

I will see if it is possible to calculate what this token is at any given time, when I find the time.

**Comment by reidarw** [comment]
I fixed it now. 
They had a similar problem in the Home Assistant integration:
https://github.com/BobTheShoplifter/HomeAssistant-Posten/issues/9

Then we can hope that Posten's API will stay like this
